name: Deploy to mmjg's site

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: pnpm install -r

      - name: release
        run: pnpm run release

      - name: Deploy to aliyun ECS
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          
          SOURCE: dist/
          TARGET: /opt/site/${{ secrets.DEPLOY_FE_TARGET }}

          SCRIPT_AFTER: |
            pm2 start /opt/site/${{ secrets.DEPLOY_FE_TARGET }}/server/main.js